### ISSUE TITLE
Location of monitoring photodiode calibration files

### ISSUE THREAD

**Issue by jchiang87** [lsst-camera-dh/harnessed-jobs#1]
A standard location needs to be found (and, presumably, this calibration has to be made).

**Comment by hneal** [comment]
Do you mean the flux calibration files? If so, then yes and please note that unlike before, these will be files used to provide the needed slit width and not the exposure time.

----- Reply message -----

**Comment by jchiang87** [comment]
These are the data that allow one to infer the incident flux at the CCD from the measured current in the monitoring photodiode.  This has been generated in the past using two photodiodes: one at the CCD location and one at the location used during the actual wavelength scan.  This needs to be performed under identical conditions with regard to slit width, lamp performance, etc..  To my knowledge no such data has been produced since 2013.

**Comment by jchiang87** [comment]
Access issues resolved in [LSSTTD-270](https://jira.slac.stanford.edu/browse/LSSTTD-270)
